title: Vchitai Blog
description: Somewhere to store my drafts

url: https://vchitai.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 9

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: vchitai
   twitter: chitai.vct
   facebook: chitai.vct
   email: chitai.vct@gmail.com

google_analytics: "UA-132061979-1"
